### ISSUE TITLE
Tighten TS compilation

### ISSUE THREAD

**Issue by the-frey** [envoylabs/whoami-ui#15]
Haven't had the kreplits to look into it yet but feels like the compiler is being lenient as anything. Need to tighten it up and get typing.

Could be wrong, but I'm not used to stuff compiling without complaint.

**Comment by ezekiiel** [comment]
I think the solution here is to run `yarn build` before committing. Otherwise it does seem like types are very loosely checked. Running that on main a couple of times I've seen type errors.

**Comment by the-frey** [comment]
Yeah I'm going to look at some TS projects from earlier this year and see what is different in my tsconfig settings
